---
homebrew_dependencies:
  - build-essential
  - file

nvm_dependencies:
  - libssl-dev

terraform_version: latest
pyenv_python_version: "3.12.13"
nvm_version: v0.40.4
node_versions:
  - "22.22.1"
  - "20.20.1"
