hosts:
  - istio.local

components:
  istio-base:
    enabled: true
    repo:
      name: istio
      url: https://istio-release.storage.googleapis.com/charts
    chart: base
    version: "1.28.3"
    release_name: istio-base
    namespace: istio-system

  istiod:
    enabled: true
    repo:
      name: istio
      url: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    version: "1.28.3"
    release_name: istiod
    namespace: istio-system
    values_file: config/values/istiod.yaml
    depends_on:
      - istio-base

  istio-gateway:
    enabled: true
    repo:
      name: istio
      url: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    version: "1.28.3"
    release_name: istio-gateway
    namespace: istio-ingress
    values_file: config/values/istio-gateway.yaml
    depends_on:
      - istiod

extra_manifests:
  - config/values/istio-default-gateway.yaml
