---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  when: upgrade_packages | bool

- name: Install essential system packages
  ansible.builtin.apt:
    name: "{{ system_packages }}"
    state: present
