---
- name: Install NVM dependencies
  ansible.builtin.apt:
    name: "{{ nvm_dependencies }}"
    state: present

- name: Download and install NVM
  become: false
  ansible.builtin.shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Add NVM to profile
  become: false
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    line: source ~/.nvm/nvm.sh
    create: true
    mode: '0644'

- name: Install Node.js versions
  become: false
  ansible.builtin.shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ item }}"
  loop: "{{ node_versions }}"

- name: Install commitizen globally
  become: false
  community.general.npm:
    name: commitizen
    global: true
    path: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_versions[0] }}/bin"
