- name: Install vim, wget, Docker, Visual Studio Code and Google Chrome.
  hosts: local
  become: true

  vars:
    current_user: "{{ linux_user }}"
    homebrew_prefix: /home/linuxbrew/.linuxbrew

  tasks:
    # Update system
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    # Install basic packages
    - name: Install vim, wget, git
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - wget
        - git
        - git-core
        - python3-full

    # Configure the necessary keys for APT
    - name: Configure Packages Keys
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        force: "{{ item.force }}"
      loop:
        - { url: 'https://download.docker.com/linux/ubuntu/gpg', dest: '/etc/apt/trusted.gpg.d/docker.asc', mode: '0644', force: true}
        - { url: 'https://packages.microsoft.com/keys/microsoft.asc', dest: '/etc/apt/trusted.gpg.d/packages.microsoft.asc', mode: '0644', force: true}
        - { url: 'https://dl.google.com/linux/linux_signing_key.pub', dest: '/etc/apt/trusted.gpg.d/google.asc', mode: '0644', force: true}

    # Docker
    - name: Install Docker dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

    - name: Add the user to Docker group
      become: true
      ansible.builtin.user:
        name: "{{ current_user }}"
        groups: docker
        append: true

    # Visual Studio Code
    - name: Add Visual Studio Code repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.asc] https://packages.microsoft.com/repos/vscode stable main'
        state: present
        filename: vscode

    - name: Install Visual Studio Code
      ansible.builtin.apt:
        name: code
        state: present

    # Google Chrome
    - name: Add Google Chrome repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main'
        state: present

    - name: Install Google Chrome
      ansible.builtin.apt:
        name: google-chrome-stable
        state: present

- name: Install Homebrew, TFEnv and PyEnv.
  hosts: local
  become: true

  vars:
    current_user: "{{ linux_user }}"
    homebrew_prefix: /home/linuxbrew/.linuxbrew
    bashrc_path: /home/{{ current_user }}/.bashrc
    brew_path: '{{ homebrew_prefix }}/bin/brew'
    terraform_version: 'latest'
    pyenv_py_ver: '3.10.11'

  tasks:
    # Homebrew
    - name: Install Homebrew dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - file

    # Download and install Homebrew
    - name: Download and install Homebrew
      become_user: "{{ current_user }}"
      ansible.builtin.shell: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      # args:
      #   executable: /bin/bash
      register: homebrew_install_output
      changed_when: homebrew_install_output.rc != 0

    - name: Add Homebrew to the PATH
      ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        line: "{{ item.line }}"
        state: present
        create: true
        mode: "0644"
      loop:
        - { path: "/home/{{ current_user }}/.zshrc", line: 'eval "$({{ homebrew_prefix }}/bin/brew shellenv)"' }
        - { path: "/home/{{ current_user }}/.bashrc", line: 'eval "$({{ homebrew_prefix }}/bin/brew shellenv)"' }

    - name: Install TFENV
      become_user: "{{ current_user }}"
      environment:
        PATH: "{{ brew_path }}:{{ ansible_env.PATH }}"
      ansible.builtin.command: |
        {{ brew_path }} install tfenv
      register: tfenv_install_output
      changed_when: tfenv_install_output.rc != 0

    - name: Install latest terraform with TFENV
      become_user: "{{ current_user }}"
      environment:
        PATH: "{{ lookup('env', 'PATH') }}:{{ ansible_env.HOME }}/.tfenv/bin"
      ansible.builtin.shell: |
        tfenv install {{ terraform_version }}
        tfenv use {{ terraform_version }}
      register: tfenv_install_terraform_output
      changed_when: tfenv_install_terraform_output.rc != 0

    - name: Install pyenv and virtualenv
      become_user: "{{ current_user }}"
      environment:
        PATH: "{{ brew_path }}:{{ ansible_env.PATH }}"
      ansible.builtin.command: |
        {{ brew_path }} install pyenv pyenv-virtualenv
      register: pyenv_install_output
      changed_when: tfenv_install_output.rc != 0

    - name: Add PyEnv init commands to the PATH
      ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        line: "{{ item.line }}"
        state: present
        create: true
        mode: "0644"
      loop:
        - { path: "/home/{{ current_user }}/.bashrc", line: 'eval "$(pyenv init --path)"' }
        - { path: "/home/{{ current_user }}/.bashrc", line: 'eval "$(pyenv virtualenv-init -)"' }

    - name: Install and set PyEnv version {{ pyenv_py_ver }}
      ansible.builtin.shell: |
        pyenv install {{ pyenv_py_ver }}
        pyenv global {{ pyenv_py_ver }}
      register: pyenv_version_config_output
      changed_when: pyenv_version_config_output.rc != 0

    # - name: Install databricks-cli
    #   ansible.builtin.shell: |
    #     pip install databricks-cli
    #   register: databricks_cli_install_output
    #   changed_when: databricks_cli_install_output.rc != 0

    # - name: Install databricks-cli
    #   become: false
    #   ansible.builtin.pip:
    #     name: databricks-cli
    #     version: "0.17.6"
    #     state: present

- name: Install NVM, Node and cz-cli.
  hosts: local
  become: false

  vars:
    nvm_version: 'v0.39.3'

  tasks:
    - name: Install NPM dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - libssl-dev
        - file

    - name: Download and install NVM
      become: false
      ansible.builtin.shell: |
        #!/bin/bash
        set -euo pipefail
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"
      register: nvm_install_output
      changed_when: nvm_install_output.rc != 0

    - name: Setup .profile
      become: false
      ansible.builtin.lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh
        create: true
        mode: "0644"

    - name: Install node
      ansible.builtin.shell: >
        . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
      args:
        executable: /bin/bash
        chdir: "{{ ansible_env.HOME }}"
        creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
      loop:
        - 18.16.0
      register: nvm_install_node_output
      changed_when: nvm_install_node_output.rc != 0

    - name: Verify that Node.js and NPM are installed
      become: false
      ansible.builtin.shell: |
        node --version
        npm --version
      register: nvm_install_node
      changed_when: nvm_install_node.rc != 0

    - name: Install commitizen-cli
      become: false
      community.general.npm:
        name: commitizen
        global: true
