name: "Commitizen Version Bump"

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  bump_version:
    name: "Bump version and create changelog"
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write

    outputs:
      bump_version: ${{ steps.cz.outputs.version }}

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: true

      - name: Print version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"